# vim:foldmethod=marker

fallback =				"\r󰖯"
separator =				''

[matching]
# matching by app_id, class or instance or sth
'balena-etcher' =               	"\r󱊟"
'Bitwarden' =                   	"\r"
'bottles' =				"\r󰼺"
'com.usebottles.bottles' =		"\r󰼺"
'com.github.hluk.copyq' =		"\r󱘣"
'duckstation-qt' =			"\r󰐔"
'com.github.tchx84.Flatseal' = 		"\r󱛟"
'org.gnome.font-viewer' =		"\r󰛖"
'heroic' =				"\r󱢿"
'imv' =					"\r"
'org.keepassxc.KeePassXC' =		"\r󱕴"
'libreoffice-calc' = 			"\r"
'LibreWolf' =				"\r󰈹"
'librewolf-default' =			"\r󰈹"
'lutris' = 				"\r󰊗"
'mpv' =					"\r"
'org.gnome.Nautilus' =          	"\r"
'io.gitlab.news_flash.NewsFlash' =	"\r󱀁" 
'org.kde.okular' =			"\r"
'pavucontrol' = 			"\r󰓃"
'pcsx2-qt' = 				"\r󰐔"
'python3' = 				"\r󰌠"
'signal' =				"\r"
'sleek' =				"\r"
'org.gnome.Software' =			"\r󱩯"
'org.gnome.Solanum' = 			"\r"
'steam' =				"\r󰓓"
'thunderbird' =                 	"\r"
'virt-manager' =	 		"\r󰍺"
'VSCodium' =				"\r󰨞"
'/Wine System Tray/' = 			"\r󰨡"
'Zotero' =				"\r"

# matching by string
'/Godot Engine/' = 			"\r" 

# Chromium and its PWAs
'Chromium-browser' =			"\r󰊯"
'/Outlook \(PWA\)/' = 			"\r󰴢"
'/Microsoft Teams/' =			"\r󰊻"

# {{{ Terminal applications
# REMEMBER - order is important, so kitty should be last

'/nvim/' =                 		"\r"
'/ranger/' =				"\r"
'kitty' =				"\r󰄛"

# }}}

# {{{ Games and Wine

'battle.net.exe' = 			"\r󰼶"
'RogueLegacy2.x86_64' =			"\r󰺷"

# }}}
