program_options:
  tray: auto
  automount: false
  notify: true
  file_manager: xdg-open
  terminal: 'alacritty --working-directory'
  # password_prompt:

notifications:
  timeout: 3

  device_mounted: 10

device_config:
  - device_file: /dev/loop0
    ignore: true
  - device_file: /dev/loop1
    ignore: true
