program_options:
  tray: auto
  automount: false
  notify: true
  file_manager: xdg-open
  terminal: 'alacritty --working-directory'
  # password_prompt:

notifications:
  timeout: 1.5

  device_mounted: 5
