# For all settings check:
# https://alacritty.org/config-alacritty.html

[general]
live_config_reload = false
ipc_socket = false

[window]
decorations = "None"
dynamic_padding = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12

# Kanagawa.nvim
[colors.primary]
background = '#1f1f28'
foreground = '#dcd7ba'
dim_foreground = "None"

[colors.search]
matches = { foreground = "#dcd7ba", background = "#2D4F67" }
focused_match = { foreground = "#dcd7ba", background = "#2D4F67" }

[colors.hints]
start = { foreground = "#FF5D62", background = "#1f1f28" }
end = { foreground = "#FF5D62", background = "#1f1f28" }

[colors.footer_bar] 
foreground = "#dcd7ba"
background = "#1f1f28"

[colors.selection]
background = '#2d4f67'
foreground = '#c8c093'

[colors.normal]
black = '#16161D'
red = '#c34043'
green = '#76946a'
yellow = '#c0a36e'
blue = '#7e9cd8'
magenta = '#957fb8'
cyan = '#6a9589'
white = '#c8c093'

[colors.bright]
black = '#727169'
red = '#e82424'
green = '#98bb6c'
yellow = '#e6c384'
blue = '#7fb4ca'
magenta = '#938aa9'
cyan = '#7aa89f'
white = '#dcd7ba'

# [colors.dim]
# black = '#727169'
# red = '#e82424'
# green = '#98bb6c'
# yellow = '#e6c384'
# blue = '#7fb4ca'
# magenta = '#938aa9'
# cyan = '#7aa89f'
# white = '#dcd7ba'

[[colors.indexed_colors]]
index = 16
color = '#ffa066'

[[colors.indexed_colors]]
index = 17
color = '#ff5d62'

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }
unfocused_hollow = false

# See: https://alacritty.org/config-alacritty-bindings.html
# TODO: turn off things I do not like
[mouse]
bindings = [
{ mouse = "Right", mods = "Control", action = "ExpandSelection" },
]

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
# NOTE me like that binding
# if feels nice        
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"

# See: https://alacritty.org/config-alacritty-bindings.html
# TODO: turn off things I do not like
[keyboard]
bindings = [
{ key = "Escape", mods = "Control|Shift", mode = "~Search", action = "ToggleViMode" },
{ key = "Space", mods = "Control|Shift", mode = "~Search", action = "None" },
]

